### PR TITLE
Feature/google calendar

### PR DESCRIPTION
**Pull request by DavidTJGriffin**

### CODE REVIEW

**Comment by Moses-Ian** [comment]
Is there a reason you merged a feature branch into another feature branch instead of develop?

**Comment by DavidTJGriffin** [comment]
Yes I figured out how to get to Google calendar API to work. I needed to test the Google's verification on the deployed web site, that's why I merged it into the feature branch instead of develop branch. Though, I figured out that we don't need verification, because it gives the user an option to trust the developer without the need for the verification html file

**Comment by Moses-Ian** [comment]
Are you able to set which branch is deployed? Or is that only me?

**Comment by DavidTJGriffin** [comment]
I am unable to change what branch it is deployed to on my end

**Pull request merged**
